# Generated by Django 5.1.7 on 2025-03-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
